solutions = [
  {
    "name": "v8",
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "deps_file": "DEPS",
    "managed": False,
    "custom_deps": {
      "v8/test/benchmarks/data": None,
      "v8/test/mozilla/data": None,
      "v8/test/test262/data": None,
      "v8/test/test262/harness": None,
      "v8/testing/gmock": None,
      "v8/third_party/android_platform": None,
      "v8/third_party/android_sdk": None,
      "v8/third_party/android_toolchain": None,
      "v8/third_party/catapult": None,
      "v8/third_party/colorama/src": None,
      "v8/third_party/fuchsia-gn-sdk": None,
      "v8/third_party/fuchsia-sdk": None,
      "v8/third_party/instrumented_libs": None,
      "v8/third_party/perfetto": None,
      "v8/third_party/protobuf": None,
      "v8/third_party/qemu-linux-arm64": None,
      "v8/third_party/qemu-linux-x64": None,
      "v8/third_party/qemu-mac-arm64": None,
      "v8/third_party/qemu-mac-x64": None,
      "v8/tools/luci-go": None,
    },
    "custom_vars": {
      "checkout_android": False,
      "checkout_fuchsia": False,
      "checkout_ios_webkit": False,
      "checkout_centipede_deps": False,
      "download_prebuilt_arm64_rust_toolchain": False,
      "download_jsfunfuzz": False,
    },
  },
]
